noxfile.py
poetry.lock
pyproject.toml

- Create `worker-manager` extra which adds exra dependencies. Only flask for now.
- Run the worker tests in nox without `worker-manager` installed so that we can verify it works with the restricted dependencies. This may not work forever, but it works for now.

create 'worker-manager' extra

---

.gitignore
Makefile

Nox is not compatible with my system's pip, and it breaks even if I instal it in my user dir.
This is much simpler, and it will work for everyone as long as they have the right version of python.
You don't have to use it, but it makes my life easier :)

create Makefile for managing venvs

---

src/saturn_engine/worker/inventories/__init__.py
src/saturn_engine/worker/inventories/dummy.py
src/saturn_engine/worker/job/__init__.py
src/saturn_engine/worker/job/memory.py

I think its best if inventory cursors remain opaque strings.
They can be json objects, es search_afters, or anything as long as they can be serialized into strings to be persisted.

inventory: the cursor is opaque

---

src/saturn_engine/worker_manager/config/declarative.py
tests/worker_manager/api/test_inventories.py

Its better to use yaml definitions in tests, so that we can use actual configuration snippets when we find bugs or whatever...

test_inventories: use yaml definitions in tests

---

src/saturn_engine/worker/inventories/__init__.py
tests/worker/inventories/test_blocking_inventory.py

I create an executor every time we call `next_batch`.
Another option is to do:
```python
@staticmethod
@cache
def get_executor() -> Executor: ...
```
And use the same executor for all calls, but then it isn't clear who should shutdown the executor.

inventories: create BlockingInventory

---

src/saturn_engine/worker/inventories/__init__.py
src/saturn_engine/worker/inventories/dummy.py
src/saturn_engine/worker/job/__init__.py
tests/worker/inventories/test_blocking_inventory.py

Was there any reasons they needed to be dicts?
I am building one right now that could be an instance of an sdk object.

rename Item.data -> Item.args

---

src/saturn_engine/core/api.py
src/saturn_engine/core/topic.py
src/saturn_engine/worker_manager/config/declarative_job.py
tests/core/test_topic_message.py
tests/worker_manager/api/test_job_definitions.py

Add `config` property to `JobSpec` so we can override some services setting on a job basis.
@KevGoDev | @mlefebvre

Add config property to JobSpec

---

src/saturn_engine/worker/executors/executable.py
src/saturn_engine/worker/executors/manager.py
src/saturn_engine/worker/executors/queue.py
src/saturn_engine/worker/pipeline_message.py
src/saturn_engine/worker/services/extras/sentry.py
src/saturn_engine/worker/services/hooks.py
src/saturn_engine/worker/services/loggers/logger.py
src/saturn_engine/worker/services/metrics/base.py
src/saturn_engine/worker/services/tracing/tracer.py
src/saturn_engine/worker/work_factory.py
tests/worker/conftest.py
tests/worker/services/test_logger.py
tests/worker/services/test_metrics.py
tests/worker/services/test_tracer.py

Refactoring, now backward compatible, but we don't use hooks in any external project anyway.
I need executable message so I can get all the metadata about where the message is coming from.

Pass an ExecutableMessage instead of PipelineMessage to hooks

---

noxfile.py
pyproject.toml
src/saturn_engine/utils/config.py
src/saturn_engine/worker/executors/executable.py
tests/utils/test_config.py
tests/worker/conftest.py
tests/worker/test_executable.py

@aviau  @jordsti for review
We can now use a message or queue to get configuration items. This allow to have contextualized config (Such as tracing settings for a specific job or specific message). As usual, everything is typed checked!
```python
tracing_config: TracingConfig = message.config.cast_namespace("tracer", TracerConfig)
```
Note: Please review #239 first, I need to rebase this PR on top of this one.

Config override from jobs and messages

---

src/saturn_engine/worker/topic.py
src/saturn_engine/worker/topics/rabbitmq.py
tests/worker/topics/test_rabbitmq_topic.py

@jordsti | @KevGoDev 
I found a bug where completed job close the topics before we process the output. When that happen and we end up publishing on a closed topic, this lead to an infinite try loop. This fix the infinite loop, another PR is coming to fix the output closed before all message are processed.

rabbitmq: Dont wait on closed topics

---

src/saturn_engine/config_definitions.py
src/saturn_engine/database.py
src/saturn_engine/default_config.py

Allow saturn users to specify a connection creator.
One use case is AWS IAM Auth which requires a fresh token for every connection.

config: allow specifying db connection creator

---

src/saturn_engine/worker/services/extras/sentry.py

We are currently generating a lot of errors since the `with_locals` option seems to be missing from our sentry client options.
I added a default value if this option is not present in our client options.

Added default value for with_locals option for sentry

---

src/saturn_engine/utils/asyncutils.py
src/saturn_engine/worker/broker.py
src/saturn_engine/worker/executors/executable.py
src/saturn_engine/worker/executors/manager.py
src/saturn_engine/worker/executors/scheduler.py
tests/worker/test_scheduler.py

Seems to be a long standing bug in Saturn, we alway had issue with cleanup up after a job or hang when killing Saturn. Turns out we were trying to `aclose` a generated being `anext` (And we can't do that). This PR fix a few issues around this:
- ExecutableQueue only wait for pending message if the message was yield. It could be cancelled while we were yielding, so we discard the pending message from the count in that case.
- While removing a job from the scheduler, we ensure there is not `anext` in progress before calling `aclose`
- We properly let the scheduler finish (By using `TasksGroupRunner.wait_all`) to give the job an opportunity to properly cleanup.

scheduler: Fix cleanup failing due to improper generator handling

---

src/saturn_engine/client/worker_manager.py
src/saturn_engine/core/api.py
src/saturn_engine/models/job.py
src/saturn_engine/stores/jobs_store.py
src/saturn_engine/worker_manager/api/jobs.py
src/saturn_engine/worker_manager/services/sync.py
tests/worker_manager/api/test_jobs.py

New API to batch load the cursors states, aka:
```
POST /api/jobs/_states/fetch
{
"cursors": {
"job-123": ["a", "b"]
}
}
200 OK
{
"cursors": {
"job-123": {"a": {"x": 1}, "b": {"x": 2}}
}
}
```

Add new /jobs/_states/fetch endpoint to batch fetch cursors states

---

src/saturn_engine/client/worker_manager.py
src/saturn_engine/utils/asyncutils.py
src/saturn_engine/worker/executors/executable.py
src/saturn_engine/worker/services/job_state/service.py
tests/utils/__init__.py
tests/utils/test_asyncutils.py
tests/worker/services/job_state/test_service.py

Add the code to fetch multiple cursors for multiples jobs at once from the Saturn worker service.

JobState: Add method to fetch cursor

---

src/saturn_engine/utils/config.py
src/saturn_engine/utils/iterators.py
src/saturn_engine/worker/job.py
tests/utils/test_iterators.py
tests/worker/test_job.py

@slaroche  @infherny 
Adding some code so I can:
* Add options to a job (inventory) through its defintion in the form of:
```
kind: JobDefitinion
spec:
template:
config:
job: {enable_states_cursors: true}
```
* Add some python utilities and logic in `Job` to buffer a bunch of message until either `buffer_size` is reached or `flush_after` has pass. This will allow to load a bunch of cursors states for many message at once.

Support buffering in job iterator

---

src/saturn_engine/utils/asyncutils.py
src/saturn_engine/worker/executors/queue.py
tests/worker/test_broker.py

Otherwise a broker doing nothing will take 10 seconds (close timeout) before giving up.

Make ExecutableQueue cancellable while polling new message

---

src/saturn_engine/core/api.py
src/saturn_engine/models/job.py
tests/worker_manager/api/test_jobs.py

Now the `/api/jobs` endpoint tells you if the job is enabled and who it is assigned to.
@aviau @infherny

api: Add queue info to jobs listing

---

src/saturn_engine/utils/__init__.py
src/saturn_engine/utils/iterators.py
src/saturn_engine/worker/inventories/fanin.py
src/saturn_engine/worker/inventories/static.py
tests/utils/test_iterators.py
tests/worker/inventories/test_fanin.py

@mlefebvre @aviau 
I need this so I can have a job with multiple inventory that all use the same cursors states. As it turns out, having multuple `inputs` on a job create many sub-jobs and does not share the same `job_definition_name`. This `FanIn` inventory seems to be the simplest way to deal with this for now without redefining too many concept...

Add fanin inventory to create a single inventory out of many

---

src/saturn_engine/worker/services/loggers/logger.py
tests/worker/services/test_logger.py

Should clena the log from high output volumes.
@infherny

Limit output logs to only 10 items

---

src/saturn_engine/worker/executors/queue.py
src/saturn_engine/worker/services/hooks.py
src/saturn_engine/worker/services/loggers/logger.py
tests/worker/services/test_hooks.py
tests/worker/services/test_logger.py

Add results_processed hook

---

src/saturn_engine/utils/asyncutils.py
src/saturn_engine/utils/tester/inventory_test.py
src/saturn_engine/worker/inventories/topic.py
src/saturn_engine/worker/inventory.py
src/saturn_engine/worker/job.py
src/saturn_engine/worker/services/job_state/store.py
tests/worker/test_job.py

@mlefebvre @infherny 
With this, the cursor is never move forward until this message (and all previous messages have been processed)
Reminder that processed -> message executed, outputs published and all the hook ran.

Move inventory cursor only once an item have been successfuly processed

---

example/definitions/simple.yaml
example/tests/pipeline_tests.yaml
src/saturn_engine/core/api.py
src/saturn_engine/utils/tester/pipeline_test.py
src/saturn_engine/worker/error_handling.py
src/saturn_engine/worker/executors/queue.py
src/saturn_engine/worker/services/extras/sentry.py
src/saturn_engine/worker/services/loggers/logger.py
src/saturn_engine/worker/services/metrics.py
src/saturn_engine/worker/topic.py
src/saturn_engine/worker/topics/memory.py
src/saturn_engine/worker/work_factory.py
src/saturn_engine/worker_manager/config/declarative_job.py
tests/utils/__init__.py
tests/worker/conftest.py
tests/worker/test_executor.py

@aviau @slaroche 
Add a few more advanced error handling, namely:
```
error::ZeroDivisionError:
- topic: logging-error
- error_handler:
set_handled: false
republish:
channel: default
max_retry: 5
```
What the code above does is:
* `topic: logging-error`: Output a message to the `logging-error` topic. This message has the `error` and `cause` attributes which is the error details and the original message causing the exception. One way to use this would be to have specific topic that can output to specific sentry or error logging system.
* `set_handled: fase`: By default any error that match one of the `error:...` channel is set as "handled". This means that services like error logging or sentry will not handle them. Metric will increment a `error_handled` metric instead of the usual …

More Error Handling

---

src/saturn_engine/utils/iterators.py
src/saturn_engine/worker/inventories/fanin.py
tests/utils/test_iterators.py
tests/worker/inventories/test_fanin.py

Similar to `FanIn` inventory, but allow settings priority to items. This is useful for the pattern where there's an inventory mixed with a recursive paging topic. The paging topic can be set with a priority `0` so it always get processed first. This should ensure it never reach a state of recursive back-pressure if the pipeline never page more than one page at a time.
There might be some rare condition where it could happen, but this is the simplest defense I could build right now.
@infherny @aviau

Add PriorityFanIn

---

src/saturn_engine/utils/__init__.py
src/saturn_engine/utils/iterators.py
src/saturn_engine/worker/context.py
src/saturn_engine/worker/executors/bootstrap.py
src/saturn_engine/worker/executors/executable.py
src/saturn_engine/worker/executors/manager.py
src/saturn_engine/worker/executors/queue.py
src/saturn_engine/worker/services/loggers/console_logging.py
src/saturn_engine/worker/services/loggers/logger.py
src/saturn_engine/worker/work_manager.py
tests/utils/test_utils.py
tests/worker/services/test_logger.py

Right now context is attached to log if they fall without the `Logger` hooks, but anything else lack context.
This PR add a new `context` module that allow any code to set the current task context that can then be reused by any other component (metrics, logger, etc.). Most log should not be tagged with their proper job or message!

Set context vars that have greater coverage and not logger specific

---

src/saturn_engine/utils/__init__.py
src/saturn_engine/worker/executors/executable.py
tests/worker/test_executable.py

Remove the need to use the empty resource pattern.
I need this since the resource are currently broken with error handling and this is quicker (and nicer) to do than refactor the whole resource setup.

Add max_concurrency to job config

---

.gitignore
example/definitions/executor.yaml
example/src/example/pipelines.py
src/saturn_engine/utils/inspect.py

Don't mind the example files, look at the `inspect.py`
I think I found why the cause of these import error when worker starts.
Seems like our race condition fix didn't work. Looking at CPython, `sys.modules` can contains partial module. At that point is also seem that `import_module` does check if the module is already completely imported before trying to import, so we might as well just use it instead of our half-baked `if mod not in sys.module: ... else return sys.module[mod]`

Fix racy inspect

---

.gitignore
example/definitions/executor.yaml
example/src/example/pipelines.py
pyproject.toml
src/saturn_engine/utils/asyncutils.py
src/saturn_engine/utils/inspect.py
src/saturn_engine/worker/executors/arq/__init__.py
src/saturn_engine/worker/executors/arq/executor.py
src/saturn_engine/worker/executors/arq/worker.py

Looking at our logs, found out that an ARQ worker dying means Saturn is going to wait for the timeout to trigger. I added a small healthcheck system for each message so we can detect when a worker processing a message went down instead of waiting for the much longer timeout. (10s vs 10m in some cases)

arq: Add healthcheck to detect when worker die

---

src/saturn_engine/utils/lru.py
src/saturn_engine/worker/executors/arq/worker.py

@infherny 
This way a custom worker could pass its own executor such as a multi process pool.

Allow custom executor

---

src/saturn_engine/worker/executors/executable.py
src/saturn_engine/worker/inventories/batching.py
src/saturn_engine/worker/inventories/chained.py
src/saturn_engine/worker/inventories/fanin.py
src/saturn_engine/worker/inventories/joined.py
src/saturn_engine/worker/inventories/topic.py
src/saturn_engine/worker/inventory.py
src/saturn_engine/worker/job.py
src/saturn_engine/worker/topic.py
src/saturn_engine/worker/topics/batching.py
src/saturn_engine/worker/topics/rabbitmq.py

Init Topics

---

src/saturn_engine/worker/executors/arq/executor.py
src/saturn_engine/worker/topics/rabbitmq.py

Add metrics about bytes transfer

---

src/saturn_engine/worker/topics/rabbitmq.py
tests/worker/topics/test_rabbitmq_topic.py

https://pika.readthedocs.io/en/stable/modules/channel.html
Seems like `exclusive` is not an expected argument.

Remove exclusive args from exchange creation

---

src/saturn_engine/worker/executors/arq/__init__.py
src/saturn_engine/worker/executors/arq/executor.py

With recent ARQ changes, it is now possible to raise `TimeoutError` from diverging values of queues and results timeouts. This aims to give us saner defaults

 Merged queue timeout and result timeout 

---

src/saturn_engine/worker_manager/services/sync.py

Handle jop failing to sync

---

Dockerfile

Reduce the number of layer in a docker image will result in a smaller docker image filesize
When doing RUN commands, each of them will create a new layer on the docker file system which will
- Increase the image size (Hence more storage cost for images and disk space used)
- Make the build a little slower
I didn't combine the poetry build statement as we want still to have incremental rebuild when doing new builds, the ADD statement caches the file and won't run the sub-sequent RUN command if nothing has changed

chore: reduce the number of layers in docker image

---

src/saturn_engine/models/queue.py
tests/models/test_queue.py

Added a unit test to make sure we raised the good exception on the missing job queue
We already test the state update thrugh integration test but we never made sure that the exception is raised for the missing job queue (the failing test)
[X] Lint passing : yes
[X] Did you run the tests ? : yes
cc @isra17 
Small note it could also be nice to add a PULL_REQUEST_TEMPLATE for projects like this especially if you don't run the tests on every push so people don't forget to run them
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

chore: simplify the join definition logic, add exception test

---

src/saturn_engine/stores/jobs_store.py

Fix cursor fetch query

---

src/saturn_engine/worker/topics/rabbitmq.py

I found a race condition in `aiormq` where `publish` (and perhaps other blocking calls) can await forever in case of rabbitmq disconnection. Even the `timeout` param is not enough to protect against this.
The internal timeout is implemented through `asyncio.wait_for` anyway, so here it is. There might be a similar issue with the consumer message ack, will have a quick look at this too.

Add timeout on publish

---

src/saturn_engine/client/worker_manager.py
src/saturn_engine/config_definitions.py
src/saturn_engine/core/api.py
src/saturn_engine/default_config.py
src/saturn_engine/stores/queues_store.py
src/saturn_engine/worker/services/api_client.py
src/saturn_engine/worker_manager/services/lock.py
tests/worker_manager/api/test_lock.py

The goal of this MR is to add the ability to lock jobs by executors.

Worker: lock jobs by executors

---

src/saturn_engine/worker/services/usage_metrics.py
src/saturn_engine/worker_manager/config/declarative_job.py
tests/worker/services/test_usage_metrics.py
tests/worker_manager/api/test_job_definitions.py

When tracking pipeline metrics, we currently can only filter down by pipeline name, executor name and job id. There is currently no way of filtering them by job name.
I would even argue that we should maybe remove the jobId from the tags, because it has a very high cardinality.
I'm not sure i'm happy with adding this field right on the QueueItem. I wonder if we should have some sort of `tags` dictionary instead containing both the executor name and the job definition name?
Another avenue would be to leverage the job labels, but i feel like this might be mixing up some concepts.

[Metrics] Add original job definition name to pipeline metrics tags

---

src/saturn_engine/models/__init__.py
src/saturn_engine/worker/services/api_client.py
src/saturn_engine/worker/worker_manager.py

since `load_static_definition` need the DB, we need to init it before calling the `StandaloneWorkerManagerClient`

Init DB before init the  StandaloneWorkerManagerClient
