Flared/saturn

- src/saturn_engine/worker/services/config.py
The rest will be provided by the worker manager.
My next PR will add yaml config parsing to the worker manager.
> worker: load config from env

- poetry.lock
- pyproject.toml
- src/saturn_engine/core/api.py
- src/saturn_engine/worker_manager/api/inventories.py
- src/saturn_engine/worker_manager/config/__init__.py
- src/saturn_engine/worker_manager/config/config.py
- src/saturn_engine/worker_manager/config/declarative.py
- src/saturn_engine/worker_manager/server.py
- tests/worker/test_broker.py
- tests/worker_manager/api/test_inventories.py
- tests/worker_manager/config/test_declarative.py
- tests/worker_manager/config/testdata/test_declarative_simple/file1.yaml
- tests/worker_manager/conftest.py
based on https://github.com/Flared/saturn/pull/33
- Load objects from `SATURN_STATIC_DEFINITIONS_DIR`
- Load object with pyyaml and desert/marshmallow
- Create inventories endpoint
> worker_manager: load static definitions

- src/saturn_engine/client/worker_manager.py
- src/saturn_engine/core/api.py
- src/saturn_engine/core/message.py
- src/saturn_engine/core/pipeline.py
- src/saturn_engine/core/resource.py
- src/saturn_engine/examples.py
- src/saturn_engine/utils/inspect.py
- src/saturn_engine/utils/options.py
- src/saturn_engine/worker/broker.py
- src/saturn_engine/worker/executable_message.py
- src/saturn_engine/worker/executors/__init__.py
- src/saturn_engine/worker/executors/process.py
- src/saturn_engine/worker/executors/simple.py
- src/saturn_engine/worker/queues/__init__.py
- src/saturn_engine/worker/resources_manager.py
- src/saturn_engine/worker/runner.py
- src/saturn_engine/worker/services/manager.py
- src/saturn_engine/worker/task_manager.py
- src/saturn_engine/worker/work_manager.py
- tests/worker/conftest.py
- tests/worker/test_broker.py
- tests/worker/test_executor.py
- tests/worker/test_resources_manager.py
- tests/worker/test_work_manager.py
This is the first PR that actually execute a pipeline in a process pool, locking its resource and all!
> worker: Acquire and attach resource to message

- src/saturn_engine/client/worker_manager.py
- src/saturn_engine/core/api.py
- src/saturn_engine/core/resource.py
- src/saturn_engine/examples.py
- src/saturn_engine/utils/__init__.py
- src/saturn_engine/utils/inspect.py
- src/saturn_engine/worker/executable_message.py
- src/saturn_engine/worker/inventories/__init__.py
- src/saturn_engine/worker/inventories/dummy.py
- src/saturn_engine/worker/job/__init__.py
- src/saturn_engine/worker/queue.py
- src/saturn_engine/worker/resources_manager.py
- src/saturn_engine/worker/scheduler.py
- src/saturn_engine/worker/task_manager.py
- src/saturn_engine/worker/topics/__init__.py
- src/saturn_engine/worker/topics/dummy.py
- src/saturn_engine/worker/topics/memory.py
- src/saturn_engine/worker/topics/rabbitmq.py
- src/saturn_engine/worker/work.py
- src/saturn_engine/worker/work_factory.py
- src/saturn_engine/worker/work_manager.py
- src/saturn_engine/worker_manager/config/declarative.py
- tests/worker/conftest.py
- tests/worker/test_broker.py
- tests/worker/test_executor.py
- tests/worker/test_memory_queues.py
- tests/worker/test_resources_manager.py
- tests/worker/test_task_manager.py
- tests/worker/test_work_manager.py
Bit of refactoring to adapt with what we spoke about the config.
Also hit a bug where test where taking way longer than they should because of a sleep in the Scheduler. I created a TasksGroup class to handle what the sleep tried to do.
> worker: Add outputs to job and renames thing to match Saturns concept

- noxfile.py
- src/saturn_engine/core/api.py
- src/saturn_engine/worker_manager/api/inventories.py
- src/saturn_engine/worker_manager/api/job_definitions.py
- src/saturn_engine/worker_manager/config/declarative.py
- src/saturn_engine/worker_manager/config/declarative_job_definition.py
- src/saturn_engine/worker_manager/config/declarative_pipeline.py
- src/saturn_engine/worker_manager/config/declarative_topic_item.py
- src/saturn_engine/worker_manager/config/static_definitions.py
- src/saturn_engine/worker_manager/server.py
- tests/worker_manager/api/test_job_definitions.py
- tests/worker_manager/config/test_declarative.py
- tests/worker_manager/conftest.py
based on https://github.com/Flared/saturn/pull/37
>  declarative config: support JobDefinitions

- Dockerfile
> Dockerfile: add build-essential

- example/definitions/simple.yaml
- example/src/example/settings.py
- src/saturn_engine/default_config.py
- src/saturn_engine/worker/services/__init__.py
- src/saturn_engine/worker/services/tracing/config.py
- src/saturn_engine/worker/services/tracing/sampler.py
- src/saturn_engine/worker/services/tracing/tracer.py
- tests/worker/services/test_tracer.py
Add a sampler that rely on Saturn config to set sample ratio.
@mlefebvre @KevGoDev  
Depends on #241
> Saturn trace sampler

- src/saturn_engine/worker/services/loggers/logger.py
- src/saturn_engine/worker/services/tracing/__init__.py
@KevGoDev | @mlefebvre for quick review
> tracing: Add traceid to logs

- src/saturn_engine/default_config.py
- src/saturn_engine/worker/services/loggers/logger.py
- src/saturn_engine/worker/services/tracing/__init__.py
More trace context in logs. Especially if the span is being sampled and remote.
> logger: Add a few trace properties

- poetry.lock
- pyproject.toml
- setup.cfg
- src/saturn_engine/utils/flask.py
- src/saturn_engine/utils/options.py
- src/saturn_engine/worker/services/tracing/sampler.py
- src/saturn_engine/worker_manager/server.py
- tests/worker/topics/test_batching_topic.py
cc @aviau 
Semantic version pining for date based versionning doesn't make sense.
> deps: Use >= for year-based versions

- src/saturn_engine/worker/executors/executable.py
- tests/worker/test_executable.py
Stacked on #253 , this PR make the executable queue waiting for all message to be completed before closing the queue outputs.
@jordsti @KevGoDev for review
> Executable queue wait for completion 

- src/saturn_engine/config_definitions.py
- src/saturn_engine/database.py
- src/saturn_engine/default_config.py
Follow-up on https://github.com/Flared/saturn/pull/256 to allow even more tweaking.
> database: even more options

- .gitignore
- example/definitions/simple.yaml
- example/src/example/pipelines.py
- example/tests/pipeline_tests.yaml
- src/saturn_engine/core/error.py
- src/saturn_engine/utils/tester/json_utils.py
- src/saturn_engine/utils/tester/pipeline_test.py
- src/saturn_engine/worker/error_handling.py
- src/saturn_engine/worker/executors/queue.py
- src/saturn_engine/worker/services/loggers/logger.py
- tests/worker/conftest.py
- tests/worker/test_executor.py
WIP
Add error output to pipelines
> Draft: Add error output

- src/saturn_engine/worker/topics/rabbitmq.py
@KevGoDev @mlefebvre 
I want to default the topic to pickle, but just switching is going to cause a lot of error as some message are still enqueued with json. But deploying this (and running it a for a few hours) we can ensure that most message will now have a proper content-type to know how to decode specific messages.
> rabbitmq: Add a message content-type to control serializer

- src/saturn_engine/worker/services/loggers/logger.py
- tests/utils/__init__.py
- tests/worker/services/test_logger.py
@aviau @KevGoDev for review
Useful to search in logs for slow tasks.
> logger: Add duration_ms to trace data

- src/saturn_engine/worker/services/loggers/logger.py
- tests/utils/__init__.py
- tests/worker/services/test_logger.py
> logger: fix duration_ms calculation

- poetry.lock
- pyproject.toml
- setup.cfg
- src/saturn_engine/models/base.py
- src/saturn_engine/utils/declarative_config.py
- src/saturn_engine/utils/tester/inventory_test.py
- src/saturn_engine/utils/tester/topic_test.py
- src/saturn_engine/worker/broker.py
- src/saturn_engine/worker/services/rabbitmq.py
- src/saturn_engine/worker/services/tracing/tracer.py
- src/saturn_engine/worker/topics/rabbitmq.py
- tests/conftest.py
- tests/utils/metrics.py
- tests/utils/tcp_proxy.py
- tests/worker/conftest.py
- tests/worker/services/test_metrics.py
- tests/worker/test_scheduler.py
- tests/worker/topics/test_rabbitmq_topic.py
- tests/worker_manager/config/test_declarative.py
@infherny @mlefebvre 
Upgrade aio-pika and fix bunch of small issues that came with the upgrade.
> Upgrade aio-pika and other packages

- pyproject.toml
- src/saturn_engine/worker/topics/rabbitmq.py
> rabbitmq: Support more queue option: x-max-length-bytes and x-overflow

- .github/workflows/tests.yml
- noxfile.py
- pyproject.toml
- src/saturn_engine/worker/services/usage_metrics.py
- tests/config.py
- tests/worker/services/test_usage_metrics.py
@mlefebvre @aviau , this metrics will be quite useful to have a look at Saturn internal and find possible stage where something is not keeping up.
> services(usage_metrics): Add a new service adding the saturn.pipelines.usage metrics

- src/saturn_engine/core/topic.py
- src/saturn_engine/worker/inventories/multi.py
- src/saturn_engine/worker/inventory.py
Otherwise it's too much work to fix existing code and quite verbose anyway.
> core: allow builting item and message from str

- src/saturn_engine/utils/asyncutils.py
- src/saturn_engine/worker/job/api.py
- tests/utils/test_asyncutils.py
- tests/utils/test_utils.py
I started working on this for the item's cursor feature.
> utils(DelayedThrottle): Fix many bugs and add more tests

- src/saturn_engine/worker/topics/rabbitmq.py
> rabbitmq: Actually log size above

- src/saturn_engine/core/api.py
- src/saturn_engine/models/queue.py
- src/saturn_engine/worker/services/hooks.py
- src/saturn_engine/worker/work_factory.py
- src/saturn_engine/worker/work_manager.py
- tests/worker/conftest.py
- tests/worker/test_broker.py
- tests/worker/test_work_manager.py
- tests/worker_manager/api/test_lock.py
In the spirit of batching things, this now allow returning cursors as part of the Lock response.
> Queue item with state

- src/saturn_engine/config_definitions.py
- src/saturn_engine/default_config.py
- src/saturn_engine/worker/services/api_client.py
- src/saturn_engine/worker/services/job_state/service.py
- src/saturn_engine/worker/services/job_state/store.py
- src/saturn_engine/worker/services/manager.py
- src/saturn_engine/worker/work_manager.py
- tests/config.py
- tests/worker/conftest.py
- tests/worker/services/job_state/test_service.py
- tests/worker/services/job_state/test_store.py
@aviau @infherny 
Add a new Saturn service to persist job state. Also make the API client a service.
> services: Add JobState service and store

- src/saturn_engine/worker/topic.py
> BlockingTopic: match OptionsSchema init signature

- src/saturn_engine/core/job_state.py
- src/saturn_engine/core/pipeline.py
- src/saturn_engine/worker/executors/bootstrap.py
- src/saturn_engine/worker/executors/queue.py
- src/saturn_engine/worker/job.py
- src/saturn_engine/worker/services/hooks.py
- src/saturn_engine/worker/services/job_state/service.py
- tests/worker/services/job_state/test_service.py
Last missing piece for Saturn!
> jobstate: Allow pipeline to yield CursorStateEvent

- src/saturn_engine/stores/jobs_store.py
> fix: Set queue as completed on job termination

- src/saturn_engine/utils/asyncutils.py
- tests/worker/test_broker.py
> asyncutils: Ensure we clear signal only after they have been waited

- src/saturn_engine/utils/iterators.py
- tests/utils/test_iterators.py
- tests/worker/services/job_state/test_service.py
> fix async_buffered to be more exact

- src/saturn_engine/client/saturn.py
A small nice improvement. This avoid creating many threads and Saturn instance.
> Make SyncSaturnClient a singleton

- src/saturn_engine/worker/services/job_state/service.py
- tests/worker/services/job_state/test_service.py
The previous design required to make sure inventory set a good `cursor` key to every message (hint: they don't).
With this I can override the state key used to retrieve the state from an inventory.
> job_state: Allow setting metadata "state_cursor" to define the state key

- src/saturn_engine/core/topic.py
- src/saturn_engine/utils/iterators.py
- src/saturn_engine/worker/executors/executable.py
- src/saturn_engine/worker/job.py
- src/saturn_engine/worker/services/hooks.py
- src/saturn_engine/worker/services/job_state/service.py
- src/saturn_engine/worker/topic.py
- tests/worker/services/job_state/test_service.py
@mlefebvre 
This allow using cursor state with Topic too.
> JobState: Move batch item hook to xmsg instead of job

- src/saturn_engine/worker/topics/rabbitmq.py
> RabbitMQTopic: Reraise PublishError

- src/saturn_engine/client/saturn.py
- tests/client/test_saturn_client.py
> Cancel publish task on client sync timeout

- src/saturn_engine/worker/topics/rabbitmq.py
> RabbitMQ: Fix broken max_length_bytes typo

- src/saturn_engine/utils/iterators.py
- src/saturn_engine/worker/executors/executable.py
- tests/worker/test_executable.py
> Handle errors from topic message context

- poetry.lock
- pyproject.toml
- src/saturn_engine/worker/services/databases.py
- tests/worker/services/test_database.py
Add a database service that can be use to get session for othen component.
> services: Add databases service

- src/saturn_engine/utils/asyncutils.py
- src/saturn_engine/worker/inventories/topic.py
- src/saturn_engine/worker/inventory.py
- src/saturn_engine/worker/job.py
- tests/utils/test_asyncutils.py
- tests/worker/inventories/test_topic.py
@mlefebvre @aviau 
Mixed with #210 this allow me to consume from inventory and topics in a single job.
> Add TopicAdapter inventory that convert a topic into an inventory

- src/saturn_engine/utils/asyncutils.py
One of the memory leak at least. This pretty much leak every message...
> Fix memory leak from Cancellable helper

- src/saturn_engine/utils/traceback_data.py
- tests/utils/test_traceback_data.py
@infherny @aviau 
`format_local` could probably be cleaner, but that's tested and good enough.
> traceback: limit locals stringification

- src/saturn_engine/core/pipeline.py
- src/saturn_engine/utils/hooks.py
- src/saturn_engine/worker/services/hooks.py
- src/saturn_engine/worker/services/manager.py
- tests/worker/services/test_hooks.py
@mlefebvre @aviau 
Useful in our case to run a job specific hook
> Add config to the Hook service to attach hook per pipeline or jobs.

- src/saturn_engine/worker/executors/queue.py
> Ensure excpetion make it to the message context

- src/saturn_engine/worker/executors/executable.py
- src/saturn_engine/worker/executors/queue.py
@mlefebvre 
With this, a TopicMessage context will return once its results have been processed.
> Message context includes results processing

- src/saturn_engine/worker/inventories/fanin.py
- tests/worker/inventories/test_fanin.py
Python is the worse.
@mlefebvre | @aviau
> Fix fanin topic not settings cursor

- src/saturn_engine/worker/executors/bootstrap.py
With this, we will be able to get the topic message in pipelines.
> Add topic message to meta args

- src/saturn_engine/worker/topics/batching.py
@infherny @slaroche 
This allow to use it with the `PriorityFanIn` and always have the iterator ready.
> Avoid using wait_for if there are items ready in the queue

- src/saturn_engine/stores/jobs_store.py
- src/saturn_engine/worker/services/job_state/service.py
- tests/worker/conftest.py
- tests/worker/services/job_state/test_service.py
- tests/worker_manager/api/test_jobs.py
@slaroche @infherny 
This make it possible to share cursors states between jobs.
> Allow override the job cursors namespace

- src/saturn_engine/worker/inventories/joined.py
- src/saturn_engine/worker/inventories/multi.py
- src/saturn_engine/worker/inventory.py
- tests/worker/inventories/test_inventory.py
- tests/worker/inventories/test_joined_inventory.py
Last PR, see https://github.com/Flared/saturn/pull/350
> Test and fix concurrent joined inventory support

- src/saturn_engine/worker/error_handling.py
- src/saturn_engine/worker/inventories/loop.py
- tests/worker/inventories/test_loop_inventory.py
@mlefebvre @aviau 
An inventory that keep on yielding until a pipeline raise a break exception.
> Add LoopInventory

- src/saturn_engine/worker/inventories/batching.py
- src/saturn_engine/worker/inventories/fanin.py
- src/saturn_engine/worker/inventory.py
- tests/worker/inventories/test_batching_inventory.py
- tests/worker/inventories/test_fanin.py
> Ensure items context are run in batch and fanin

- src/saturn_engine/worker/services/job_state/service.py
- src/saturn_engine/worker/services/job_state/store.py
- tests/worker/conftest.py
- tests/worker/services/job_state/test_service.py
The last bug
@francoismasson @sebd11
> Load state from cache

- example/definitions/executor.yaml
- example/definitions/join-and-loop.yaml
- example/src/example/pipelines.py
- src/saturn_engine/worker/inventories/joined.py
- src/saturn_engine/worker/inventories/loop.py
- src/saturn_engine/worker/inventories/multi.py
- src/saturn_engine/worker/inventory.py
- src/saturn_engine/worker/services/hooks.py
- tests/worker/inventories/test_joined_inventory.py
- tests/worker/inventories/test_loop_inventory.py
- tests/worker/services/test_hooks.py
> Inventory use events instead or exception

- src/saturn_engine/worker/inventories/chained.py
- tests/worker/inventories/test_chained_inventory.py
Cursor would always be set to `None`...
> Fix chained cursor

- README.md
- example/definitions/simple.yaml
- example/src/example/pipelines.py
- example/src/example/resources.py
- src/saturn_engine/core/pipeline.py
- src/saturn_engine/worker/executors/executable.py
- src/saturn_engine/worker/executors/queue.py
- src/saturn_engine/worker/resources/manager.py
@mlefebvre As requested!
See the `example` files for how to use.
> Add non-persisted state to resource

- src/saturn_engine/worker/services/usage_metrics.py
> Add metrics to track time spent processing results

- src/saturn_engine/worker/topics/rabbitmq.py
> Add bind_arguments to rabbitmq queue

- src/saturn_engine/worker/topics/rabbitmq.py
> Fix rabbitmq topic

- src/saturn_engine/worker/executors/queue.py
- src/saturn_engine/worker/services/_metrics/base.py
- src/saturn_engine/worker/services/hooks.py
- src/saturn_engine/worker/services/metrics.py
- src/saturn_engine/worker/services/usage_metrics.py
- tests/worker/services/test_metrics.py
- tests/worker/services/test_usage_metrics.py
> Add more usage metrics for publishing message

- src/saturn_engine/worker/executors/arq/executor.py
> ARQ: Clear the executor queue before starting the executor

- .gitignore
- docs/example/how_to/cancel.py
- docs/how_to/cancelled-job.rst
- docs/how_to/index.rst
- src/saturn_engine/core/pipeline.py
- src/saturn_engine/worker/executors/arq/__init__.py
- src/saturn_engine/worker/executors/arq/executor.py
- src/saturn_engine/worker/executors/arq/worker.py
> executor cancel message on worker dying

- src/saturn_engine/core/pipeline.py
- tests/core/test_pipeline.py
> Fix CancellationToken serialization

- src/saturn_engine/core/topic.py
- src/saturn_engine/database.py
- src/saturn_engine/utils/asyncutils.py
- src/saturn_engine/utils/options.py
- src/saturn_engine/utils/tester/json_utils.py
- src/saturn_engine/worker/broker.py
- src/saturn_engine/worker/executors/arq/executor.py
- src/saturn_engine/worker/inventory.py
- src/saturn_engine/worker/services/__init__.py
- src/saturn_engine/worker/services/usage_metrics.py
- src/saturn_engine/worker_manager/config/declarative.py
- src/saturn_engine/worker_manager/config/static_definitions.py
- tests/conftest.py
- tests/worker/test_broker.py
- tests/worker/test_executor.py
- tests/worker/test_pipeline_info.py
- tests/worker/topics/conftest.py
- tests/worker/topics/test_batching_topic.py
> Fix redis import

- src/saturn_engine/core/api.py
- src/saturn_engine/core/types.py
- src/saturn_engine/stores/jobs_store.py
- src/saturn_engine/utils/config.py
- src/saturn_engine/worker/services/job_state/service.py
- tests/worker/conftest.py
- tests/worker/services/job_state/test_service.py
Does steps 1 and 2 of https://github.com/Flared/saturn/issues/408
@sebd11 @bendoyon
> JobState support multiple cursors format

- src/saturn_engine/core/api.py
- src/saturn_engine/worker/services/job_state/service.py
- src/saturn_engine/worker/services/job_state/store.py
- tests/worker/services/job_state/test_service.py
Does steps 3 and 4 of https://github.com/Flared/saturn/issues/408
Last code needed to fix the cursor issue
@sebd11 @bendoyon
> Format cursor before saving them

- src/saturn_engine/models/base.py
- src/saturn_engine/models/compat.py
- src/saturn_engine/models/job.py
- src/saturn_engine/models/job_cursor_state.py
- src/saturn_engine/models/queue.py
- tests/conftest.py
- tests/worker/conftest.py
- tests/worker/inventories/test_joined_inventory.py
- tests/worker/inventories/test_loop_inventory.py
- tests/worker/inventories/test_periodic_inventory.py
- tests/worker/test_executable.py
- tests/worker/test_executor.py
- tests/worker/test_resources_manager.py
- tests/worker/test_scheduler.py
- tests/worker/topics/test_blocking_topic.py
- tests/worker/topics/test_periodic_topic.py
The current code fails with SQLAlchemy 1.4
> Fix sqla compat

- src/saturn_engine/worker/job.py
- tests/worker/test_job.py
> Completed job once all message are processed

- src/saturn_engine/worker/executors/arq/__init__.py
- src/saturn_engine/worker/executors/arq/executor.py
@isra17 @infherny up for review
> Add timeout delay as a configuration job option

- src/saturn_engine/worker/executors/arq/executor.py
> ARQ use context options for result timeout

- src/saturn_engine/core/job_state.py
- src/saturn_engine/worker/services/job_state/service.py
- tests/worker/services/job_state/test_service.py
> service(State): Allow to override the updated state cursor

- example/src/example/pipelines.py
- src/saturn_engine/worker/broker.py
- src/saturn_engine/worker/work_manager.py
Fix the bug where a worker manager downtime crash all saturn worker.
> Gracefully handle lock error

- example/definitions/executor.yaml
- src/saturn_engine/worker/executors/arq/executor.py
> Limit redis connection pool max connection

- src/saturn_engine/worker/worker_manager.py
- src/saturn_engine/worker_manager/api/jobs.py
- src/saturn_engine/worker_manager/context.py
- src/saturn_engine/worker_manager/server.py
- tests/config.py
- tests/worker_manager/api/test_jobs.py
- tests/worker_manager/conftest.py
The goal is to refresh the topology when sync jobs is call
> Load patches in static definition
